### ISSUE TITLE
Map attribution for OSM, contributors... should be correct and in German finally

### ISSUE THREAD

**Issue by traveller195** [colouring-cities/colouring-dresden#19]
**Describe the problem**
The attribution of the map should be in german and also correct. 
In the moment, there is also the information for borough data ... for other London related maps.

see
/var/www/colouring-dresden/app/src/frontend/map/layers

**Comment by matkoniecz** [comment]
Attribution texts is one more candidate for config files...

**Comment by traveller195** [comment]
I changed and translated all attribitions for currently used maps and services...
