### ISSUE TITLE
bugfix of account usage/ log in/ registration/ edit function

### ISSUE THREAD

**Issue by traveller195** [colouring-cities/colouring-dresden#3]
in the current version of Colouring Dresden (based not on new clean repo/ version end of january 2023) some critical behaviour of the application can be detected:
after filling in log in data in login.html nothing happens. No message, no new page is coming.
after sign up/ register a new account, a white blank page appears 
<b>
to dos:
check, if new user was created within database
check suitable PostgreSQL migrations/ prepared SQL commands, which could help
</b>
is any service, port, etc. not running, which is relevant for acount management? perhaps in the virtual machine?

**Comment by traveller195** [comment]
notes:
- ports etc. should not be the problem (5432 for db, 3000 for app)
- check warnings / log-files of npm install... figure out relevant npm packages for login/ account/...
- check F12 in browser while this error occures
- debug platform in dev env... log files

**Comment by traveller195** [comment]
- check warnings while setting up the platform in summer 2022 --> log files.. which packages hat some warnings/ troubles?

**Comment by traveller195** [comment]
now, after setting up a clean Colouring Core (16th feb 2023) the following error occures after login or sign up:

![grafik](https://user-images.githubusercontent.com/57902113/219583208-e71cb0b4-9cc5-4cce-a6fc-dffb4b8a150b.png)

**Comment by traveller195** [comment]
to do
check also, if database setup and all up-migrations were done successfuly?
compare https://github.com/colouring-cities/colouring-dresden/tree/main/migrations 
"Create an app user:"

**Comment by traveller195** [comment]
also check, if all relevant database tables were filled with data at the beginning, for example while importing building geometries.
is there any other db table, which needs initial data?

should the INDEX applied again after data import?

**Comment by traveller195** [comment]
again:
after Sign up... "you must logged in" error occures in console log within the firefox browser
![grafik](https://user-images.githubusercontent.com/57902113/220120342-2257494c-dbdd-4cea-af62-fd7551942ccf.png)

maybe the reason is, because inside IOR intranet only http as protocoll is used?

**Comment by traveller195** [comment]
I guess the http protocoll could be the reason, why login data can not be transfered

![grafik](https://user-images.githubusercontent.com/57902113/220121871-ec21f5ac-bfcc-4585-b5b2-06adebe6aff7.png)

**Comment by tomalrussell** [comment]
Hi @traveller195 - HTTP is likely part of the problem - can you redirect all traffic to HTTPS? This would be strongly preferred, especially as the app handles user emails and passwords.

See background documentation on how the browser handles cookies: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies

The API server is using [`express-session`](http://expressjs.com/en/resources/middleware/session.html) to handle the session cookies, configured in [`app/src/server.tsx#L27-L44`](https://github.com/colouring-cities/colouring-dresden/blob/094bfcf79a44a2e8375b4aa91f73dfc29ed2b38c/app/src/server.tsx#L27-L44) and used for example in [`app/src/api/api.ts#L28-L40`](https://github.com/colouring-cities/colouring-dresden/blob/094bfcf79a44a2e8375b4aa91f73dfc29ed2b38c/app/src/api/api.ts#L28-L40). `HTTPOnly` is set by default and `Secure` is true in production.

**Comment by traveller195** [comment]
thanks @tomalrussell  I will check it.

+++++
current state is the following:

our instance is now available: 
please check:
**colouring.dresden.ioer.de**

sign up is working in the background, so in db table "user" a new account was created. But after confirmation of sign up only those error "must be logged in" occures...

I will work on it, also on your hints @matkoniecz @tomalrussell

**Comment by matkoniecz** [comment]
Note that there were some fixes that were fixing very related issue - see https://github.com/colouring-cities/colouring-core/pull/1035 and https://github.com/colouring-cities/colouring-core/issues/1024


Is it possible that you run code without including them? (though "based not on new clean repo/ version end of january 2023" would suggest that it should be already in)

**Comment by tomalrussell** [comment]
Okay, I can confirm I can create a user account and the login form submission `POST`s to the API, successfully returning my user ID, but not setting the `cl.session` cookie. 

I presume this is due to something in the server or proxy configuration. Is `APP_COOKIE_SECRET` set in the app server's environment? Is there a proxy server that might not be forwarding headers from the app?

![colouring-dresden-login-failure](https://user-images.githubusercontent.com/2762769/220144528-b1acdb2a-5b9f-48ab-b653-f5be4ad3a085.png)


Set-Cookie is the important response header here, following the same flow from https://colouring.london/login.html:

![colouring-london-login-success](https://user-images.githubusercontent.com/2762769/220144537-950314fb-8f65-4cc9-af9c-8aa358ece187.png)

**Comment by traveller195** [comment]
@tomalrussell 
yes, for APP_COOKIE_SECRET there is a random long secret given in the environment config file. 

So, perhaps, the problem could be proxy/ firewall settings. We will test it.
thanks a lot, so far!

**Comment by traveller195** [comment]
here some notes from our admin at IOER:

**- APP COOKIE SECERT value is set**
**- he not believe, that proxy is the reason. Because within IOER intranet (without https, only http), this error is the same
like here**



![grafik](https://user-images.githubusercontent.com/57902113/220343370-7024f37e-80aa-49d5-8f15-c7fae70638ea.png)


so, I / we keep working on it to solve this issue...

**Comment by traveller195** [comment]
further idea: reason could be the usage of HTTP instead HTTPS for OpenStreetMap base services

**Comment by traveller195** [comment]
issue could be solved, according to HTTP/ HTTPS

**Comment by grubl2f** [comment]
related workarounds for debugging purposes (topic: `HttpOnly`, i.e. server-only accessible cookies mentioned by @tomalrussell):
- envvar: AI_COOKIE_SECURE=0 (`env AI_COOKIE_SECURE=0 npm start`)
- edit `server.js`: `ai.cookie.secure=0`

related issue: [Unable to log in to CL website after importing database dump into CASA server #333](https://github.com/colouring-cities/colouring-core/issues/333)

**Comment by traveller195** [comment]
@grubl2f thanks for your hint. Currently it is working using https for dev and prod env
