### ISSUE TITLE
Init loading issue/ white map field... compiling problem? css minimizer plugin issue?

### ISSUE THREAD

**Issue by traveller195** [colouring-cities/colouring-dresden#45]
**Describe the problem**
Ater compiling a new production build, sometimes the following problem occures:
- within IOR intranet: page loading is without problems
- outside: for initial loading of Colouring Dresden platform: the map field is only white without base map layer... 
- after click on one of the coloured data categories everything works fine and map is shown including buildings, legend etc.

Warning in production build compiling:
Css Minimizer Plugin: Ignoring local source map at "bootstrap.min.css.map" as resource is missing.

**More information**
maybe compare: https://github.com/pkp/healthSciences/issues/117

**Comment by traveller195** [comment]
problem sometimes initial loading of main page (with welcome text)
![grafik](https://user-images.githubusercontent.com/57902113/222007459-78a9be4b-6136-4208-982c-b0ef479b26d7.png)

after click to one of the coloured data categories... the map will be shown as well
![grafik](https://user-images.githubusercontent.com/57902113/222007534-49f9daef-7e1b-4be4-8b4c-2f1f7bd7e95d.png)

**Comment by traveller195** [comment]
error messsage shown in firefox dev tools on console (while the white map problem happens)
![grafik](https://user-images.githubusercontent.com/57902113/222007866-a7c9e64e-5b6f-4aa9-95be-aaa6f4679f4c.png)

in the last days, this problem could be "solvec" as a workaroung to just do a production build again... but now, also several new production buildes could not fix it...

**Comment by traveller195** [comment]
maybe broken production build? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_token

**Comment by traveller195** [comment]
https://stackoverflow.com/questions/32031255/syntax-error-expecting-expression-got-while-trying-to-run-reactjs-tutoria

**Comment by traveller195** [comment]
maybe this could be helpful 
https://github.com/btholt/complete-intro-to-react-v4/issues/3

**Comment by traveller195** [comment]
this could be the proper answer to this issue:
https://stackoverflow.com/questions/53106643/syntax-error-in-react-app-only-on-first-load



I think the problem is cache + some non-existing script file.

1) If a local script file is missing it will probably handle it as a regular React application request and will return something starting with <!DOCTYPE html>, why you get the SyntaxError as it tries to parse the response as JS.

**2) Additionally I think it has something to do with caching some parts of the application. Probably on your deploy you remove the old files, but the application is still looking for the old files with some previous hash: main.XXXXX.js. But during the deploy you removed those files completely and uploaded new scripts: main.YYYYYY.js.**

Check the developer tools that all scripts return the expected JS file response and in case any of them are missing make appropriate changes to your cache headers and/or deployment scripts.

**Comment by traveller195** [comment]
with white map issue (firefox dev tools for network analysis)
![grafik](https://user-images.githubusercontent.com/57902113/222011745-55f0975b-84b3-4c82-a5e6-c51acd5f32ed.png)

with second load... it succed. Compare differences of loaded JS files (there is an old version of compiled JS in browser cache?)

![grafik](https://user-images.githubusercontent.com/57902113/222012000-8d605612-82ef-4c91-bee2-bb84cb869d12.png)


so, it could be more a caching problem of client after a new deployed build. not a compiling issue of prod build!

**Comment by tomalrussell** [comment]
Hi @traveller195 - I think it’s super helpful leaving your notes and learning here, keep going! 

Because you say the error only occurs outside the intranet, I would look at the gateway server cache behaviour again, as suggested in the SO answer you link to above.

The production build produces new JS/CSS files with a short random string in each filename. The HTML served from the app (and NGINX) then refers to the new files. If the gateway server is serving cached HTML responses, the browser will try to request the old JS/CSS, and may fail. Once the gateway cache is refreshed, the problem would go away.

The warning about a missing source map is just a warning, and can be ignored as long as you don’t need to inspect the bootstrap CSS in production.

**Comment by traveller195** [comment]
further solutions:
- restart all of pm2 
- avoid caching in gateway
